### ISSUE TITLE
A new function to get grade from a student   

### ISSUE THREAD

**Issue by carlosdelfino** [patrickpollet/moodlews#2]
Hello Patrick.

I am developing some new functions for the Webservice official Moodle 2.0, I'm still an apprentice in development for Moodle and I was fortunate to find work and that will be inspiring to see mine.

Congratulations on your initiative and thank you for making it public.

I'm having trouble desenvovler a function that allows me to get the grade from a student, I published a first function and in https://github.com/SistemaAula/WebService-Moodle/blob/master/SistemaAula/grade/externallib.php and I would like you to have your suggestion of what might be wrong.

In some cases it returns the correct grade, but in some cases it returns an error, stating that the value is invalid, the message follows more accurate and TXT file exported from the notes.

**Comment by carlosdelfino** [comment]
Nome,Sobrenome,Número de identificação,Instituição,Departamento,Endereço de email,Lição:Conceitos de Controle de Versão,Lição:Instalando o GIT no OS X,Lição:Instalando o GIT no Linux,Lição:Instalando o GIT no Windows,Lição:Criando Seu Primeiro Repositório Local,Lição:Criando Seu Primeiro Repositório Remoto,Tarefa:Lembrando o que foi feito, o comando "git log",Tarefa:Adicionando novos Arquivos trabalhados, o comando "git add",Tarefa:Depositando arquivos adicionados, o comando "git commit",Tarefa:Removendo tracked files ou diretórios,Lição:Desfazendo Commits,Lição:Levando minhas modificações para outros branchs sem depositar (commit)  ,Total do curso
Rogerio,Amaral,,,,rogerio@desenvolvedores.com,-,-,-,-,-,-,-,-,-,-,-,-,-
Fabiano,Campos,,,,fabiano.a.campos@gmail.com,99.00,-,-,-,-,-,-,-,-,-,44.00,-,71.50
Carlos,Delfino,,,,consultoria@carlosdelfino.eti.br,40.00,100.00,100.00,34.00,100.00,23.00,100.00,100.00,100.00,100.00,23.00,100.00,76.67
Juliana ,Queiroz,,,,juliana@desenvolvedores.com,32.00,100.00,32.00,99.00,100.00,100.00,57.00,75.00,56.00,56.00,5.00,44.00,63.00
Admin,User,,,,consultoria@carlosdelfino.eti.br,-,-,-,-,-,-,-,-,-,-,-,-,-

**Comment by carlosdelfino** [comment]
error in soap: 
SOAP-ENV:EnvelopeSOAP-ENV:BodySOAP-ENV:Fault<faultcode>Receiver</faultcode><faultstring>Invalid external api response: grade (Resposta externa da api inválida)</faultstring>/SOAP-ENV:Fault/SOAP-ENV:Body/SOAP-ENV:Envelope

**Comment by patrickpollet** [comment]
Hello, 

since you have only occasional the error , I suspect that in some circustances your function get_final_grade_by_user_id_and_course_id($userid,$courseid) does not returns a value that can be checked as a float  by the  Moodle REST Server basd on what you have declared get_final_grade_by_user_id_and_course_id_returns 

Moodle 2.0 is really picky about this and does abort if the input parameters or some return values do not check their declaration.
Actually it use a call to the same parameter cleanings function that thoses under of PHP scripts ( required_param('PARAM_XXX, ....)
the error you rececieve means exactly that 

so what you should do is 

1) relax the type declaration of the final return (a quick fix to see is that improves things) ; it that case your Soap client will likely complains if it has also strict float parsing

for example  
return new external_single_structure(
        array(
                    'grade' => new external_value(PARAM_CLEAN,"A nota final do usuário" )
        ), 'Grade com detalhes da avaliação do usuário.'
        );

2) you should always use  the four parameters version  of new external_value  

```
public function __construct($type, $desc='', $required=VALUE_REQUIRED,
        $default=null, $allownull=NULL_ALLOWED) {   
```

   'grade' => new external_value(PARAM_FLOAT,"A nota final do usuário" ,VALUE_OPTIONAL,-1)
so if your function does not return a float is will default to -1

3) finally double check the last lines of your get_final_grade_by_user_id_and_course_id 

```
            else if(!isset($grades->grade))   <--- a value can be set and empty !!!
        $result['grade'] = -1;
    else{     
        $result['grade'] = $grades->grade;
    }
```

I would write if (is_numeric($grades->grade)) instead

Cheers.

BTW : what I do in my place to here me debug these tricky calls  if to add to my Moodle config.php the following function that dum whatever I want in a file in moodledata by a simple call to 

pp_debug(' some text', $aphpvariable); 

$CFG->pp_debug=true; // change to false when no debug wanted 

function pp_error_log ($intro,$ex) {
        global $CFG;
       if (! $CFG->pp_debug) return; 
        if (is_object($ex) || is_array($ex)){
                $info=print_r((array)$ex,true);
        }else $info=$ex."\n";
        error_log (time().' : ' .$intro.' : '.$info,3,$CFG->dataroot.'/pp_debug_errors.log' );
}

so in your case I would add to the end of your function

pp_debug ('end of, **FUNCTION**);
pp_debug('crude grade from moodle ', $grades);
pp_debug('final ', $result); 
return $result;

Cheers

**Comment by carlosdelfino** [comment]
Thanks for the reply.

I'll make changes to the code today and give you a return.

In case of item 3, I think that the condition may be removed with the fix suggested in item 2.

I'll study a little more debugging features, there are several functions, but I think that can be enlarged.

**Comment by carlosdelfino** [comment]
I think this a bug on regrade process.

If I use a return time like PARAM_CLEAN this a deprecated type, then I try with PARAM_RAW, but this have unwanted side effect, because the values ​​are returned as a string.

Studying the  regrade process code, I found a function that solved the problem, your name is grade_floatval($number) is a simple function to round the numbers of grids matched to the database to the default format for MOODLE, however it just adjusting all values ​​to me in order to become really float.

Thank you a lot for your attention.

**Comment by patrickpollet** [comment]
It would be nice to publish on github yourfinal  working version 

your github repo is mot anymore valable

cheers

**Comment by carlosdelfino** [comment]
Good morning!

https://github.com/SistemaAula/WebService-Moodle

I leave the invitation to participate as well and I hope will soon be able to collaborate with your project.

Thank you for your attention.
