### ISSUE TITLE
has_role_incourse

### ISSUE THREAD

**Issue by crepit** [patrickpollet/moodlews#4]
has_role_incourse will always return true because get_primaryrole_incourse returns 0 if user exists but does not have a role in a course.

**Comment by patrickpollet** [comment]
Oups, indeed the code is a bit crude ; this operation is crude anyway, since it does not pay attention all possibilities of roles & capabilities, but it gives a rough idea of the user's status .

it should be near line 932 of server.class.php 

return ($tmp>0 && $tmp <= $roleid);

Let me know if it suits you and i shall commit a patch

Cheers.

Cheers.

**Comment by crepit** [comment]
Hi Patrick,

That should take care of it.

Thanks,

Mike

**Comment by patrickpollet** [comment]
ok committed and closed

Thanks
